name: Shell Commands

on:
  worflow_dispatch:
    types: [build]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string 
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v